# Site settings
title: "shakyshane.com"
email: shakyshane@gmail.com
description: "Building things with Javascript."
baseurl: ""
url: "http://shakyhane.com"
twitter_username: shaneosbourne
github_username:  shakyshane

exclude: ["node_modules", "gulpfile.js", "package.json"]

# Build settings
markdown: kramdown
permalink: pretty

# Assets
cssFile: "/css/main.min.css"
env: "production"
