title: shakyshane.com
email: "shakyshane@gmail.com"
description: Building things with Javascript.
baseurl: ""
url: "http://shakyhane.com"
twitter_username: shaneosbourne
github_username: shakyshane
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - bower_components
markdown: kramdown
permalink: pretty
cssFile: "https://s3-eu-west-1.amazonaws.com/shakshane/main.min-eb00a287.css"
env: production